name: ekart
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8
#-------------Packages---------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.7.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  lottie: ^3.3.2
  # Icons

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8


  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1




  # Product Specific.





  #-----------------./ Packages End ---------------

dev_dependencies:
  flutter_test:
    sdk: flutter











  
  flutter_lints: ^6.0.0





flutter:

  uses-material-design: true
  #------------Local Assets ---------#
  assets:
  - assets/logos/
  - assets/icons/
  - assets/images/on_boarding_images/
  - assets/images/animations/


#--------------Local fonts-------------#


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
